-------------------------------
---- Sites
-------------------------------

INSERT INTO site VALUES ('Bwin')     ON CONFLICT DO NOTHING;
INSERT INTO site VALUES ('Betano')   ON CONFLICT DO NOTHING;
INSERT INTO site VALUES ('Betclic')  ON CONFLICT DO NOTHING;
INSERT INTO site VALUES ('Solverde') ON CONFLICT DO NOTHING;
INSERT INTO site VALUES ('Moosh')    ON CONFLICT DO NOTHING;
INSERT INTO site VALUES ('Betway')   ON CONFLICT DO NOTHING;


-------------------------------
---- Colors
-------------------------------

INSERT INTO color VALUES ('White',    16777215) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Red',      16711680) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Orange',   16740352) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Yellow',   16776960) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Cyan',      4379892) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Blue',      4416472) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Navy',          117) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Green',     3978315) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Lime',     12578629) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Mint',     11206595) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Pink',     15741670) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Purple',    8388736) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Lavender', 14466815) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Maroon',    8388608) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Olive',     8421376) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Apricot',  16767153) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Brown',    10117924) ON CONFLICT DO NOTHING;
INSERT INTO color VALUES ('Gray',      8421504) ON CONFLICT DO NOTHING;
